=== AtB-AS/planner-web/orgs/schema-validation.json
{
  "$ref": "#/definitions/OrgData",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "OrgData": {
      "additionalProperties": false,
      "properties": {
        "fylkeskommune": {
          "additionalProperties": false,
          "properties": {
            "logoSrc": {
              "type": "string"
            },
            "logoSrcDark": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          },
          "required": ["name", "logoSrc", "logoSrcDark"],
          "type": "object"
        },
        "featureConfig": {
          "type": "object",
          "properties": {
            "replaceTitleWithLogoInHeader": {
              "type": "boolean"
            },
            "forceTheme": {
              "type": "string",
              "enum": ["light", "dark"]
            },
            "enableShowTripPatternPrice": {
              "type": "boolean"
            }
          },
          "required": ["enableShowTripPatternPrice"]
        },
        "orgId": {
          "enum": ["atb", "fram", "nfk", "troms", "vkt", "farte"],
          "type": "string"
        },
        "authorityId": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        },
        "supportEmail": {
          "type": "string"
        },
        "urls": {
          "additionalProperties": false,
          "properties": {
            "accessibilityStatementUrl": {
              "$ref": "#/definitions/TranslatableUrl"
            },
            "facebookLink": {
              "type": "string"
            },
            "instagramLink": {
              "type": "string"
            },
            "privacyDeclarationUrl": {
              "$ref": "#/definitions/TranslatableUrl"
            },
            "supportUrl": {
              "$ref": "#/definitions/TranslatableUrl"
            },
            "helpUrl": {
              "$ref": "#/definitions/TranslatableUrl"
            },
            "twitterLink": {
              "type": "string"
            },
            "homePageUrl": {
              "properties": {
                "name": {
                  "type": "string"
                },
                "href": {
                  "type": "string"
                }
              }
            },
            "purchaseTicketUrl": {
              "$ref": "#/definitions/TranslatableUrl"
            },
            "androidAppUrl": {
              "$ref": "#/definitions/TranslatableUrl"
            },
            "iosAppUrl": {
              "$ref": "#/definitions/TranslatableUrl"
            },
            "ticketInfoUrl": {
              "$ref": "#/definitions/TranslatableUrl"
            },
            "sitemapUrls": {
              "dev": {
                "name": {
                  "type": "string"
                }
              },
              "staging": {
                "name": {
                  "type": "string"
                }
              },
              "prod": {
                "name": {
                  "type": "string"
                }
              }
            }
          },
          "required": [
            "privacyDeclarationUrl",
            "accessibilityStatementUrl",
            "supportUrl"
          ],
          "type": "object"
        },
        "journeyApiConfigurations": {
          "additionalProperties": false,
          "properties": {
            "waitReluctance": {
              "type": "number"
            },
            "walkingReluctance": {
              "type": "number"
            },
            "transferPenalty": {
              "type": "number"
            },
            "defaultTransferSlack": {
              "type": "number"
            }
          },
          "type": "object"
        }
      },
      "required": ["featureConfig", "orgId", "supportEmail", "urls"],
      "type": "object"
    },
    "TranslatableUrl": {
      "additionalProperties": false,
      "properties": {
        "default": {
          "type": "string"
        },
        "en-US": {
          "type": "string"
        },
        "no": {
          "type": "string"
        },
        "nn": {
          "type": "string"
        }
      },
      "required": ["default"],
      "type": "object"
    }
  }
}

=== AtB-AS/planner-web/orgs/vkt.json
{
  "$schema": "./schema-validation.json",

  "orgId": "vkt",
  "authorityId": "VKT:Authority:VKT_ID",

  "supportEmail": "post@vkt.no",

  "fylkeskommune": {
    "logoSrc": "/vestfold_fylkeskommune.svg",
    "logoSrcDark": "/vestfold_fylkeskommune.svg",
    "name": "Vestfold fylkeskommune"
  },

  "featureConfig": {
    "enableShowTripPatternPrice": false,
    "forceTheme": "light"
  },

  "urls": {
    "privacyDeclarationUrl": {
      "default": "https://www.vkt.no/vilkaar-og-personvern/personvern/"
    },

    "accessibilityStatementUrl": {
      "default": "https://www.vkt.no/om-oss/tilgjengelighetserklaering/"
    },

    "supportUrl": {
      "default": "https://www.vkt.no/om-oss/kontakt-oss/",
      "en-US": "https://www.vkt.no/english/"
    },
    "homePageUrl": {
      "name": "vkt.no",
      "href": "https://vkt.no"
    },
    "ticketInfoUrl": {
      "en-US": "https://www.vkt.no/english/",
      "nn": "https://www.vkt.no/reise/billetter-og-priser/",
      "default": "https://www.vkt.no/reise/billetter-og-priser/"
    },
    "sitemapUrls": {
      "dev": "http://localhost:3000",
      "staging": "https://vkt-staging.planner-web.mittatb.no/",
      "prod": "https://reise.vkt.no/"
    }
  },
  "journeyApiConfigurations": {
    "waitReluctance": 1.0,
    "walkingReluctance": 4.0,
    "transferPenalty": 0,
    "defaultTransferSlack": 0
  }
}

=== AtB-AS/planner-web/orgs/fram.json
{
  "$schema": "./schema-validation.json",

  "orgId": "fram",
  "authorityId": "MOR:Authority:MOR",

  "supportEmail": "fram@mrfylke.no",

  "fylkeskommune": {
    "logoSrc": "/fram_mor_fylkeskommune.svg",
    "logoSrcDark": "/fram_mor_fylkeskommune_dark.svg",
    "name": "Møre og Romsdal fylkeskommune"
  },

  "featureConfig": {
    "replaceTitleWithLogoInHeader": true,
    "enableShowTripPatternPrice": true,
    "disableBoatComboPriceSearch": false
  },

  "urls": {
    "privacyDeclarationUrl": {
      "default": "https://frammr.no/personvern"
    },

    "accessibilityStatementUrl": {
      "default": "https://uustatus.no/nb/erklaringer/publisert/7d09e41a-8b28-4bc9-b5d2-a6bc8432f2cf"
    },

    "supportUrl": {
      "default": "https://reise.frammr.no/contact",
      "en-US": "https://reise.frammr.no/contact"
    },
    "homePageUrl": {
      "name": "frammr.no",
      "href": "https://www.frammr.no/"
    },
    "ticketInfoUrl": {
      "en-US": "https://frammr.no/billettar/billettar-og-prisar/?sprak=3",
      "nn": "https://frammr.no/billettar/billettar-og-prisar/?sprak=11",
      "default": "https://frammr.no/billettar/billettar-og-prisar/"
    },
    "purchaseTicketUrl": {
      "en-US": "https://frammr.no/tickets/how-to-buy-a-ticket/?sprak=3",
      "nn": "https://frammr.no/billettar/slik-kjoper-du-billett/",
      "default": "https://frammr.no/billettar/slik-kjoper-du-billett/"
    },
    "sitemapUrls": {
      "dev": "http://localhost:3000",
      "staging": "https://fram-staging.planner-web.mittatb.no/",
      "prod": "https://reise.frammr.no/"
    },
    "androidAppUrl": {
      "default": "https://play.google.com/store/apps/details?id=no.mrfylke.fram.production"
    },
    "iosAppUrl": {
      "default": "https://apps.apple.com/no/app/fram/id6447612651"
    }
  },
  "journeyApiConfigurations": {
    "waitReluctance": 1.0,
    "walkingReluctance": 4.0,
    "transferPenalty": 0,
    "defaultTransferSlack": 0
  }
}

=== AtB-AS/planner-web/orgs/farte.json
{
  "$schema": "./schema-validation.json",

  "orgId": "farte",
  "authorityId": "TEL:Authority:TFK_ID",

  "supportEmail": "farte@telemarkfylke.no ",

  "fylkeskommune": {
    "logoSrc": "/telemark_fylkeskommune.svg",
    "logoSrcDark": "/telemark_fylkeskommune.svg",
    "name": "Telemark fylkeskommune"
  },

  "featureConfig": {
    "forceTheme": "light",
    "enableShowTripPatternPrice": false
  },

  "urls": {
    "privacyDeclarationUrl": {
      "default": "https://www.farte.no/vilkaar-og-personvern/"
    },

    "accessibilityStatementUrl": {
      "default": "https://www.farte.no/om-farte/tilgjengelighetserklaering/"
    },

    "supportUrl": {
      "default": "https://www.farte.no/kundeservice/",
      "en-US": "https://www.farte.no/english/"
    },
    "homePageUrl": {
      "name": "farte.no",
      "href": "https://www.farte.no/"
    },
    "ticketInfoUrl": {
      "nn": "https://www.farte.no/kundeservice/billetter-og-priser/",
      "default": "https://www.farte.no/kundeservice/billetter-og-priser/"
    },
    "sitemapUrls": {
      "dev": "http://localhost:3000",
      "staging": "https://farte-staging.planner-web.mittatb.no/",
      "prod": "https://reise.farte.no/"
    }
  },
  "journeyApiConfigurations": {
    "waitReluctance": 1.0,
    "walkingReluctance": 4.0,
    "transferPenalty": 0,
    "defaultTransferSlack": 0
  }
}

=== AtB-AS/planner-web/orgs/nfk.json
{
  "$schema": "./schema-validation.json",
  "orgId": "nfk",
  "authorityId": "NOR:Authority:12",

  "supportEmail": "sentrumsterminalen@boreal.no",

  "fylkeskommune": {
    "logoSrc": "/nfk_fylkeskommune.svg",
    "logoSrcDark": "/nfk_fylkeskommune_dark.svg",
    "name": "Nordland fylkeskommune"
  },

  "featureConfig": {
    "enableShowTripPatternPrice": true,
    "disableBoatComboPriceSearch": false
  },

  "urls": {
    "privacyDeclarationUrl": {
      "default": "https://www.reisnordland.no/personvern-og-cookies"
    },

    "accessibilityStatementUrl": {
      "default": "https://uustatus.no/nb/erklaringer/publisert/ae5bc315-272a-469e-b4cb-8ba5164ea988"
    },

    "supportUrl": {
      "default": "https://www.reisnordland.no/kontaktskjema",
      "en-US": "https://www.reisnordland.com/contact-us"
    },

    "instagramLink": "https://www.instagram.com/reisnordland",
    "facebookLink": "https://www.facebook.com/ReisNordland",
    "homePageUrl": {
      "name": "reisnordland.no",
      "href": "https://www.reisnordland.no/"
    },
    "ticketInfoUrl": {
      "en-US": "https://www.reisnordland.no/priser-pa-buss",
      "no": "https://www.reisnordland.no/priser-pa-buss",
      "default": "https://www.reisnordland.no/priser-pa-buss"
    },
    "purchaseTicketUrl": {
      "en-US": "https://www.reisnordland.no/kjop-bussbillett",
      "no": "https://www.reisnordland.no/kjop-bussbillett",
      "default": "https://www.reisnordland.no/kjop-bussbillett"
    },
    "sitemapUrls": {
      "dev": "http://localhost:3000",
      "staging": "https://nfk-staging.planner-web.mittatb.no/",
      "prod": "https://reise.reisnordland.no/"
    },
    "androidAppUrl": {
      "default": "https://play.google.com/store/apps/details?id=no.reisnordland.reis.production"
    },
    "iosAppUrl": {
      "default": "https://apps.apple.com/no/app/reis/id1574137854"
    }
  },
  "journeyApiConfigurations": {
    "waitReluctance": 1.0,
    "walkingReluctance": 4.0,
    "transferPenalty": 0,
    "defaultTransferSlack": 0
  }
}

=== AtB-AS/planner-web/orgs/atb.json
{
  "$schema": "./schema-validation.json",
  "orgId": "atb",
  "authorityId": "ATB:Authority:2",

  "supportEmail": "kundeservice@atb.no",

  "fylkeskommune": {
    "logoSrc": "/trl_fylkeskommune.svg",
    "logoSrcDark": "/trl_fylkeskommune_dark.svg",
    "name": "Trøndelag fylkeskommune"
  },

  "featureConfig": {
    "enableShowTripPatternPrice": true,
    "disableBoatComboPriceSearch": true
  },

  "urls": {
    "privacyDeclarationUrl": {
      "default": "https://www.atb.no/vilkar/personvernerklaering-for-kundetjenester/"
    },

    "accessibilityStatementUrl": {
      "default": "https://uustatus.no/nb/erklaringer/publisert/2eb632a6-8e02-4d83-bdc3-3d9901f079bd"
    },

    "supportUrl": {
      "default": "https://atb.no/kundeservice/",
      "en-US": "https://www.atb.no/en/customer-service/"
    },
    "facebookLink": "https://www.facebook.com/atb.no/",
    "instagramLink": "https://www.instagram.com/atb_no/",
    "twitterLink": "https://twitter.com/atb_no",
    "homePageUrl": {
      "name": "atb.no",
      "href": "https://atb.no/"
    },
    "ticketInfoUrl": {
      "en-US": "https://www.atb.no/en/fares/",
      "no": "https://www.atb.no/priser/",
      "default": "https://www.atb.no/priser/"
    },
    "sitemapUrls": {
      "dev": "http://localhost:3000",
      "staging": "https://atb-staging.planner-web.mittatb.no/",
      "prod": "https://reise.atb.no/"
    },
    "purchaseTicketUrl": {
      "en-US": "https://www.atb.no/en/ticket/",
      "no": "https://www.atb.no/billett/",
      "default": "https://www.atb.no/billett/"
    },
    "androidAppUrl": {
      "default": "https://play.google.com/store/apps/details?id=no.mittatb.store"
    },
    "iosAppUrl": {
      "default": "https://apps.apple.com/us/app/atb/id1502395251"
    }
  },
  "journeyApiConfigurations": {
    "waitReluctance": 1.0,
    "walkingReluctance": 4.0,
    "transferPenalty": 0,
    "defaultTransferSlack": 120
  }
}

=== AtB-AS/planner-web/orgs/troms.json
{
  "$schema": "./schema-validation.json",
  "orgId": "troms",
  "authorityId": "TRO:Authority:1",

  "supportEmail": "",

  "featureConfig": {
    "enableShowTripPatternPrice": false
  },

  "urls": {
    "privacyDeclarationUrl": {
      "default": "https://svipper.no/meny/hjelp-og-kontakt/personvern-og-transportvilkar/"
    },

    "accessibilityStatementUrl": {
      "default": "https://svipper.no/"
    },

    "supportUrl": {
      "default": "https://svipper.no/meny/hjelp-og-kontakt/",
      "en-US": "https://svipper.no/menu/help-and-contact/?sprak=3"
    },

    "homePageUrl": {
      "name": "svipper.no",
      "href": "https://www.svipper.no/"
    },
    "ticketInfoUrl": {
      "en-US": "https://svipper.no/meny/billetter-og-priser/?sprak=3",
      "no": "https://svipper.no/meny/billetter-og-priser/",
      "default": "https://svipper.no/meny/billetter-og-priser/"
    },
    "purchaseTicketUrl": {
      "en-US": "https://svipper.no/menu/tickets/how-to-buy-tickets/",
      "no": "https://svipper.no/meny/billetter-og-priser/slik-kjoper-du-billett/",
      "default": "https://svipper.no/meny/billetter-og-priser/slik-kjoper-du-billett/"
    },
    "sitemapUrls": {
      "dev": "http://localhost:3000",
      "staging": "https://troms-staging.planner-web.mittatb.no/",
      "prod": "https://reise.svipper.no/"
    },
    "androidAppUrl": {
      "default": "https://play.google.com/store/apps/details?id=PLACEHOLDER_TROMS"
    },
    "iosAppUrl": {
      "default": "https://apps.apple.com/no/app/svipper/id6502283055"
    }
  },
  "journeyApiConfigurations": {
    "waitReluctance": 1.0,
    "walkingReluctance": 4.0,
    "defaultTransferSlack": 0
  }
}
